Updated the project settings to Xcode 12
ggirotto/MultipleSimulators pull request #2
Opened 2020-08-12 13:23 UTC by noorulain17

2020-08-14 13:49 UTC, ggirotto commented
@noorulain17 Thanks for the PR! Could you please update with a .gitignore so these `xcshareddata` stop getting tracked?

2020-08-14 13:49 UTC, ggirotto requested changes
Thanks for the PR! Could you please update with a .gitignore so these xcshareddata stop getting tracked?

2020-08-16 11:13 UTC, noorulain17 commented
> Thanks for the PR! Could you please update with a .gitignore so these xcshareddata stop getting tracked?

Done

2020-08-16 12:47 UTC, ggirotto approved these changes

2020-08-17 11:39 UTC, merged